version: '3'

services:
  db:
    image: postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql
    restart: always
    ports:
      - "5432:5432"

  web:
    image: app
    container_name: qweeze
    build: .
    command: ./run_docker.sh
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db