# Generated by Django 2.2.5 on 2019-09-05 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EURCurrency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('delete_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('quantity', models.SmallIntegerField()),
                ('value', models.SmallIntegerField(choices=[(5, '5 EUR'), (10, '10 EUR'), (20, '20 EUR'), (50, '50 EUR'), (100, '100 EUR'), (200, '200 EUR'), (500, '500 EUR')], unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RUBCurrency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('delete_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('quantity', models.SmallIntegerField()),
                ('value', models.SmallIntegerField(choices=[(5, '5 RUB'), (10, '10 RUB'), (50, '50 RUB'), (100, '100 RUB'), (200, '200 RUB'), (500, '500 RUB'), (1000, '1000 RUB'), (2000, '2000 RUB'), (5000, '5000 RUB')], unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='USDCurrency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('delete_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('quantity', models.SmallIntegerField()),
                ('value', models.SmallIntegerField(choices=[(1, '1 USD'), (2, '2 USD'), (5, '5 USD'), (10, '10 USD'), (20, '20 USD'), (50, '50 USD'), (100, '100 USD')], unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
